services:
  app:
    image: overhours
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

secrets:
  sentry-auth-token:
    environment: "SENTRY_AUTH_TOKEN"
