version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/golang:1.11
      - image: circleci/mongo:4.0.5
    working_directory: /go/src/github.com/Team6083/OverHours
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Go Get Dep
          command: go get -u https://github.com/golang/dep
      - run:
          name: run build
          command: |
            dep ensure
            go build -v
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...
      - save_cache:
          keys:
            - v1-pkg-cache
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results
  deploy:
    <<: *container_config
    steps:
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master