import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';

import { Inter } from 'next/font/google';
import './globals.css';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from '@mui/material';

import appTheme from '@/theme';
import { auth } from '@/auth';
import { UserInfo } from '@/types';
import AppNav from './AppNav';
import { NotistackProvider } from './SnackbarProviderClient';

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'OverHours - CMS Robotics',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  let user: UserInfo | undefined;
  if (session?.user) {
    const id = session.user.id ?? session.user.email ?? session.user.name ?? undefined;

    if (id === undefined) {
      throw new Error('User ID is required');
    }

    user = {
      id,
      name: session.user.name ?? undefined,
      email: session.user.email ?? undefined,
      avatar: session.user.image ?? undefined,
    };
  }

  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={appTheme}>
            <CssBaseline enableColorScheme />
            <SessionProvider>
              <AppNav user={user} />
              <NotistackProvider>
                {children}
              </NotistackProvider>
            </SessionProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
