import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

import { Inter } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from "@mui/material";

import theme from '@/theme';
import LayoutClient from "./LayoutClient";
import { getSession } from "./lib/session";
import AppNav from "./AppNav";

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "OverHours - CMS Robotics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getSession();
  console.log('session', session);

  const userInfo = {
    name: 'John Doe',
    avatarSrc: '/static/images/avatar/2.jpg'
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline enableColorScheme />
            <AppNav userInfo={userInfo} />
            <LayoutClient>
              {children}
            </LayoutClient>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
