import { ComponentProps } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import { Box, Breadcrumb, Container } from "@chakra-ui/react";

import { Provider } from "@/components/ui/provider"
import AppNav from "./AppNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider> {/* Chakra-UI provider */}
          <SessionProvider> {/* Auth.js provider, for useSession() hook */}
            <Container maxWidth="5xl" fluid p={4} my={2}>
              <Box mb={4}>
                <AppNav />
                {/* <Breadcrumbs /> */}
              </Box>
              {children}
            </Container>
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}

function Breadcrumbs(props: {} & ComponentProps<typeof Breadcrumb.Root>) {
  const { ...rootProps } = props;

  return <Breadcrumb.Root {...rootProps}>
    <Breadcrumb.List>
      <Breadcrumb.Item>
        <Breadcrumb.Link asChild><Link href="/">Home</Link></Breadcrumb.Link>
      </Breadcrumb.Item>
      <Breadcrumb.Separator />
      <Breadcrumb.Item>
        <Breadcrumb.Link asChild><Link href="/logs">Logs</Link></Breadcrumb.Link>
      </Breadcrumb.Item>
      <Breadcrumb.Separator />
      <Breadcrumb.Item>
        <Breadcrumb.CurrentLink>Props</Breadcrumb.CurrentLink>
      </Breadcrumb.Item>
    </Breadcrumb.List>
  </Breadcrumb.Root>;
}
