openapi: 3.0.0
info:
  version: "1.0.0-SNAPSHOT-oas3"
  title: OverHours REST API
  description: ''


servers:
  - url: 'https://virtserver.swaggerhub.com/kennhung/OverHours/1.0.0-SNAPSHOT'
  - url: 'http://virtserver.swaggerhub.com/kennhung/OverHours/1.0.0-SNAPSHOT'